### ISSUE TITLE
R build failing with Error: `Error in loadNamespace(x) : there is no package called ‘testrmd’`

### ISSUE THREAD

**Issue by westonpace** [apache/arrow-cookbook#17]
I was hoping this was just intermittent since there was no actual code change but it's happened 3 times in a row now so I'm not sure what could have caused it.

**Comment by thisisnic** [comment]
Had a look into this and it's caused by a failure to install an R package called `pacman` which then loads the `testrmd` package if it isn't already installed.  Whilst it should hopefully be intermittent, refactoring the script to not use it is pretty trivial, so I'll do that anyway as it reduces our dependencies.

**Comment by DrLuong** [comment]
I also have same problem
Error in loadNamespace(x) : there is no package called ‘bookdown’

**Comment by thisisnic** [comment]
@DrLuong Thanks for reporting this!  As this is a different problem, would you mind opening a new ticket?
